services:
  yolo-detector:
    build: .
    container_name: proyecto-deteccion
    ports:
      - "8501:8501"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/app
    devices:
      - /dev/video0:/dev/video0
    privileged: true
    stdin_open: true
    tty: true
